sequences:
    - protein:
        id: "A"
        sequence: "PANLLTSLVRAHLDSGPSTAKLDYSKFQELVLPHFGKEDAGDVQQFYDLLSGSLEVIRKWAEKIPGFAELSPADQDLLLESAFLELFILRLAYRSKPGEGKLIFCSGLVLHRLQCARGFGDWIDSILAFSRSLHSLLVDVPAFACLSALVLITDRHGLQEPRRVEELQNRIASCLKEHVAAVAGASCLSRLLGKLPELRTLCTQGLQRIFYLKLEDLVPPPPIIDKIFMDTLPF"
    - protein:
        id: "B"
        sequence: "ANLLTSLVRAHLDSGPSTAKLDYSKFQELVLPHFGKEDAGDVQQFYDLLSGSLEVIRKWAEKIPGFAELSPADQDLLLESAFLELFILRLAYRSKPGEGKLIFCSGLVLHRLQCARGFGDWIDSILAFSRSLHSLLVDVPAFACLSALVLITDRHGLQEPRRVEELQNRIASCLKEHVAAVASCLSRLLGKLPELRTLCTQGLQRIFYLKLEDLVPPPPIIDKIFMDTLPF"
    - ligand:
        id: "C"
        smiles: "c1(oc2C=CC=Cc2c1NC(=O)CC1=COC2=C1C=C(C=C2)CC)C(=O)C1=CC=C(C=C1)F"